---
title: "graphs_model_development_accuracies"
author: "CGG"
date: "2023-05-11"
output: html_document
---

```{r}
library(tidyverse)  # include packages 
library(gt)
library(ggplot2)
library(dplyr)
library(stringr)
library(here)
library(colorspace)

library(patchwork)
```

```{r}
accs <- read_csv(here('data','accuracies_feature_experiments.csv'))
accs
```

```{r}
add_window_size <- function(df){
  df$window_size = str_split_i(df$features, "_", -1) %>%  as.numeric()
  return(df)
}

avg_ent <- accs[5:17,]
avg_ent$type = 'avg_ent'
avg_ent <- add_window_size(avg_ent)

glcm <- accs[18:30,]
glcm$type = 'glcm'
glcm <- add_window_size(glcm)

entr <- accs[31:43,]
entr$type = 'entr'
entr <- add_window_size(entr)

avg <- accs[44:56,]
avg$type = "avg"
avg <- add_window_size(avg)

# ------------------------------------------
  
all <- bind_rows(avg, entr, avg_ent, glcm)
all$type <- factor(all$type, 
                      levels = c("glcm","avg","entr","avg_ent"))

```

```{r}
avg %>% 
  ggplot( aes(x=window_size, y=acc)) +
    geom_line( color="grey") +
    geom_point(shape=21, color="black", fill="#69b3a2", size=3) +
  labs( y="Overall accuracy (%)", 
        x="Length of window side (pixels)")+
  scale_x_continuous(
    breaks=seq(5,25,4),
    #labels=c("5x5", "9x9","13x13","17x17","21x21","25x25")
    ) +
  theme_light() +   
    ggtitle("Overal Accuracy")
```


```{r}
accuracy_graph <- function(which_acc, y_label, title){
  all %>% 
  ggplot( aes(x = window_size, 
              y = which_acc, 
              color = type,
              shape = type)) +
    geom_line( color = "grey") +
    geom_point(size=4) +
  labs( y = y_label, 
        x = "Window side length (pixels)",
        title = title,
        subtitle = subtitle)+
  # scale_shape_discrete(
  #   name = "Texture Features Added",
  #   labels = c("GLCM", "Average", "Entropy", "Average and Entropy")
  # )+
 # scale_shape_manual(values=c(15, 16, 15, 8))+
  guides(color="none", shape = "none")+
  scale_x_continuous(
    breaks=seq(5,25,4))+
  scale_color_brewer(palette = "Set1")+
  theme_light() +
  theme(legend.position = "bottom")
}


```

```{r}
# ------------------------------------------
title = "(e) Overall Accuracies for Texture Features Across Window Sizes"
subtitle =  ""
y_label = "Overall accuracy (%)"

OA <-   all %>% 
  ggplot( aes(x = window_size, 
              y = acc, 
              color = type,
              shape = type)) +
    geom_line( color = "grey") +
    geom_point(size=4) + 
  labs( y = y_label, 
        x = "Window side length (pixels)",
        title = title,
        subtitle = subtitle)+
  scale_shape_discrete(
    name = "Texture Features Added",
    labels = c("GLCM", "Average", "Entropy", "Average and Entropy")
  )+
 # scale_shape_manual(values=c(15, 16, 15, 8))+
  guides(color="none")+
  scale_x_continuous(
    breaks=seq(5,25,4))+
  scale_color_brewer(palette = "Set1")+
  theme_light() +
  theme(legend.position = "bottom")

OA
```


```{r}
point_colors <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442")


all %>% 
# --------------------------------
  ggplot( aes(x = window_size, 
              y = acc,
              group=type)) +
# --------------------------------
  geom_line( color = "grey") +
# --------------------------------
  geom_point(size = 4,
             aes(shape = type,  # color, shape and fill depend on type
                 fill = type,
                 color= type),
             alpha=0.8)  + # transparency value for all points
# --------------------------------
  # shape
  scale_shape_manual(
    name = NULL,
    values = c(21,22,23,24)
  ) +
# --------------------------------  
  # inner color
   scale_fill_manual(
    name = NULL,
    values = point_colors
  )+
# --------------------------------  
  # borders
  scale_color_manual(
    name = NULL,
    values = darken(point_colors, 0.3)
  ) + 
# --------------------------------
  labs( y = y_label, 
        x = "Window side length (pixels)",
        title = title,
        subtitle = subtitle)+
# --------------------------------  
  scale_x_continuous(
    breaks=seq(5,25,4))+
# --------------------------------
  # guides(
  #   color="none")+
  guides(
    color = guide_legend(
      nrow=1,
      override.aes = list(
        shape = c(21,22,23,24)
      )
    )
  ) +
# --------------------------------  
  theme_light() +
# --------------------------------  
  theme(legend.position = "bottom",
        legend.text = element_text(size = 15))

  
```


```{r}
# ------------------------------------------
title =  "(a) Iceplant Producer's Accuracies for Texture Features Across Window Sizes"
subtitle =  ""
y_label = "Producer's accuracy (%)"
ice_PA <- accuracy_graph(all$prod_acc_P, y_label, title)

# ------------------------------------------
title =  "(b) Other Vegetation Producer's Accuracies for Texture Features Across Window Sizes"
subtitle =  ""
y_label = "Producer's accuracy (%)"
veg_PA <- accuracy_graph(all$prod_acc_N, y_label, title)

# ------------------------------------------
title =  "(c) Iceplant User's Accuracies for Texture Features Across Window Sizes"
subtitle =  ""
y_label = "User's accuracy (%)"
ice_UA <- accuracy_graph(all$user_acc_P, y_label, title)

# ------------------------------------------
title =  "(d) Other Vegetation User's Accuracies for Texture Features Across Window Sizes"
subtitle =  ""
y_label = "User's accuracy (%)"
veg_UA <- accuracy_graph(all$user_acc_N, y_label, title)
```

```{r}

setEPS()
postscript("gfg.eps", width=7, height = 4)
(ice_PA + veg_PA)/ (ice_UA + veg_UA)/OA
dev.off()
```

```{r}
(ice_PA + veg_PA)/ (ice_UA + veg_UA)/OA
```

